/**
 * KeycapStudio – Export Package
 *
 * One-click delivery export: triggers three sequential downloads:
 *   1. {preset}_{legend}.stl  – 3D geometry (STL binary)
 *   2. {preset}_{legend}.png  – 2D legend image (PNG at 4× scale)
 *   3. {preset}_{legend}.svg  – 2D legend vector (SVG)
 *
 * Filenames are generated by makeExportNames() (P6 naming rule).
 * Downloads are triggered with a small delay so browsers don't coalesce them.
 */

import { exportPNG } from './PNGExporter.js';
import { exportSVG } from './SVGExporter.js';
import { exportSceneSTL } from '../csg/csgEvaluator.js';
import { makeExportNames } from '../io/filename.js';

const DOWNLOAD_DELAY_MS = 400;

/**
 * Trigger all three delivery downloads for the current keycap asset.
 *
 * @param {object}   kcs      – current KCS document (shape3d + legend2d)
 * @param {object}   project  – 2D project object (projectStore.project shape)
 * @param {object}   scene    – 3D scene document (from sceneStore.scene)
 * @param {function} [onStage] – optional callback(stageText) for progress updates
 */
export async function exportPackage(kcs, project, scene, onStage) {
  const { stl, png, svg } = makeExportNames(kcs);

  // 1. STL
  await exportSceneSTL(scene, stl, onStage);

  // 2. PNG @4x (delay so the browser handles the first download)
  onStage?.('Exporting PNG…');
  await new Promise(resolve => setTimeout(resolve, DOWNLOAD_DELAY_MS));
  exportPNG(project, 4, false, png);

  // 3. SVG
  onStage?.('Exporting SVG…');
  await new Promise(resolve => setTimeout(resolve, DOWNLOAD_DELAY_MS));
  exportSVG(project, false, svg);
}
